#开发环境配置
server:
    port: 8080
    #context-path: /eba

#spring
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: ebei-eba

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/eba?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
      host: 193.112.130.59
      port: 6378
      password: 123456
      pool:
        max-idle: 10
        max-active: 10
        max-wait: 1000

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ebei.eba.module.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging 打印sql日志
logging:
  #config: classpath:log/logback.xml
  level:
    com:
      ebei:
        eba:
          mapper: debug

eureka:
  client:
      register-with-eureka: false
      fetch-registry: false
